import Head from "next/head";
import styles from "../styles/globals.module.scss";
import NavBar from "@/components/NavBar";
import Banner from "@/components/Banner";
import { Feed } from "@/components/Feed";
import axios from "axios";
import { Fragment, useEffect } from "react";
import { useDispatch } from "react-redux";
import { allPosts } from "@/redux/filterSlice";

export default function Home({ data }) {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(allPosts(data));
  }, [dispatch, data]);
  return (
    <Fragment>
      <Head>
        <title>ATG WORLD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://media.licdn.com/dms/image/C510BAQFO1hAAXUH7qw/company-logo_100_100/0/1575358701761?e=1693440000&v=beta&t=Hb6583J_N39LeL_iwiBseXc8d4TRbvgEfs7XpcfSR-A"
        />
      </Head>
      <main className={styles.body}>
        <NavBar />
        <Banner />
        <Feed />
      </main>
    </Fragment>
  );
}
export async function getServerSideProps() {
  const response = await axios.get("http://localhost:3000/api/posts");

  return { props: { data: response.data } };
}
